# Generated by Django 3.1.5 on 2021-01-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='image',
        ),
    ]
