# Generated by Django 3.1.5 on 2021-01-14 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0002_remove_details_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('url', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Типы оплаты',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Тип кузова', 'verbose_name_plural': 'Типы кузова'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Типы загрузки', 'verbose_name_plural': 'Типы загрузки'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'verbose_name': 'Директоры и диспетчеры', 'verbose_name_plural': 'Директоры и диспетчеры'},
        ),
        migrations.RenameField(
            model_name='freight',
            old_name='world_premiere',
            new_name='date_off',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='city',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='fees_in_usa',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='fess_in_world',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='freight',
            name='tagline',
        ),
        migrations.AddField(
            model_name='freight',
            name='city1',
            field=models.CharField(default='', max_length=100, verbose_name='Загрузка'),
        ),
        migrations.AddField(
            model_name='freight',
            name='city2',
            field=models.CharField(default='', max_length=100, verbose_name='Выгрузка'),
        ),
        migrations.AddField(
            model_name='freight',
            name='date_to',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата загрузки'),
        ),
        migrations.AddField(
            model_name='freight',
            name='sum',
            field=models.PositiveIntegerField(default=0, help_text='указывать сумму в рублях', verbose_name='Ставка'),
        ),
        migrations.AddField(
            model_name='freight',
            name='weight',
            field=models.PositiveIntegerField(default=0, help_text='указывать в тоннах', verbose_name='Масса груза'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='freights.category', verbose_name='Тип кузова'),
        ),
        migrations.AlterField(
            model_name='freight',
            name='workers',
            field=models.ManyToManyField(related_name='freight_worker', to='freights.Worker', verbose_name='директор'),
        ),
    ]
