# Generated by Django 3.1.5 on 2021-01-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0003_auto_20210114_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='pays',
            field=models.ManyToManyField(to='freights.Pays', verbose_name='типы оплаты'),
        ),
    ]
