# Generated by Django 3.1.5 on 2021-01-14 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freights', '0004_freight_pays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freight',
            name='year',
        ),
    ]
